sudo: required

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

cache:
  directories:
    - "$HOME/google-cloud-sdk/"
install:
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; curl https://sdk.cloud.google.com | bash; fi
  # Add gcloud to $PATH
  - source /home/travis/google-cloud-sdk/path.bash.inc
  - gcloud version
  - gcloud --quiet components update kubectl
  # Auth flow
  - echo $GCLOUD_KEY | base64 --decode > gcloud.json
  - cat gcloud.json
  - gcloud auth activate-service-account $GCLOUD_EMAIL --key-file gcloud.json


deploy:
  - docker build -t gcr.io/calcoasttech/calcoasttech.com .
  - gcloud docker push gcr.io/calcoasttech/calcoasttech.com > /dev/null