sudo: required

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

before_install:
  - docker build -t docker_image .
  - echo ${GOOGLE_SERVICEACCOUNT_JSON} > /tmp/keyfile.json
  - docker login -u _json_key --password-stdin https://gcr.io < /tmp/keyfile.json

deploy:
  provider: script
  script:  
    - docker tag docker_image gcr.io/rightscale-bryankaraffa/calcoasttech.com:latest
    - docker push gcr.io/rightscale-bryankaraffa/calcoasttech.com:latest
  on:
    branch: master